name: my_new_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  stream_chat_flutter: ^9.17.0
  rating_dialog: ^2.0.4
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/